DROP DATABASE IF EXISTS dbData;

CREATE DATABASE dbData;
USE dbData;

CREATE TABLE tbUsuario(
COD_USER INT PRIMARY KEY AUTO_INCREMENT,
NOME_USER VARCHAR(50) NOT NULL,
CARGO_USER VARCHAR(50) NOT NULL,
DATA_USER DATE
);



